### PR TITLE
added cuda macro equivalents to build libraries and executable

### PR DESCRIPTION
**Pull request by mwerlberger**
I didn't add the FindCuda stuff yet to the catkin_simple ecosystem but I would like to move some macros from my libraries into catkin_simple so that working with cuda and catkin_simple gets even easier. I will create another pull request with the find stuff later....

### CODE REVIEW

**Comment by wjwwood** [comment]
This looks cool, thanks for the pr!

My first reaction is that this belongs in it's own package, since it probably should have a dependency on some CUDA software which we'd not want to introduce to `catkin_simple`. The same could be said of all the ROS specific stuff `catkin_simple` does though, so it's a bit of a hypocritical position.

Still I'd rather see how we could change `catkin_simple` to accomodate this feature as an external extension of `catkin_simple`. Could you provide an example snippet of CMake which demonstrates how this would work as proposed. Presumably you'd need to `find_package(CUDA)` or something like that first.

**Comment by mwerlberger** [comment]
I agree that this part is still missing. I currently have my own package with cmake macros where I do the `find_package(CUDA)` and related compiler flags for nvcc, etc. I was thinking about a standalone package (e.g. `cuda_catkin`) that includes all the cuda stuff and relies on `catkin_simple` but adding the additional macros. But of course it would be handy to have it somehow tightly coupled with `catkin_simple`. For me even better would be that we automatically check if there are cuda files like `*cu;*.cuh` and if there are any automagically use the cuda scripts when invoking `cs_add_library`, etc. What do you think?

**Comment by mwerlberger** [comment]
hmm? :)

**Comment by wjwwood** [comment]
I still think this would be better as an external package. Introducing it into `catkin_simple` directly doesn't seem like a good idea to me.

> For me even better would be that we automatically check if there are cuda files like _cu;_.cuh and if there are any automagically use the cuda scripts when invoking cs_add_library, etc. 

I'd rather find a way to make this possible without adding cuda specifics inside of `catkin_simple`.

I'd also still like to see a cmake snippet of this in use:

> Could you provide an example snippet of CMake which demonstrates how this would work as proposed. Presumably you'd need to find_package(CUDA) or something like that first.

**Comment by mwerlberger** [comment]
@wjwwood it is ok if you don't wanna include it into catkin_simple but I think it would be a great feature if it was in there....

Anyway, no cuda specifics inside is difficult because cuda needs different add_library and add_target macros (cuda_add_library and cuda_add_target). There are possible ways to pre-compile all the cuda files and just pass the object files to the respective cs_\* macros but it is not the nicest way to do so... But we could work around this to have additional macros that internally call the catkin_simple stuff?

For finding cuda I currently use [this macro](https://github.com/mwerlberger/imp/blob/develop/imp_cmake/cmake/macros/imp_finders.cmake#L4-L101).

**Comment by wjwwood** [comment]
As the current pull request stands, the new functions `cs_cuda_add_executable` and `cs_cuda_add_library` can be offered in a separate package, which can depend on CUDA and even automatically invoke a macro like the one you linked to in order to find CUDA for the user. The later two things being something that I think most catkin_simple users would not desire out-of-the-box.

If you have a concrete suggestion as to how we can change catkin_simple to better accommodate these functions as external additions to the catkin_simple API I'd be happy to consider it, but if the proposal is to just integrate these functions into catkin_simple as is, I'd prefer to not do that.

I appreciate the pull request and I hope you understand my desire to keep the package lightweight on functions and dependencies.

**Comment by mwerlberger** [comment]
ok. I'll create an extra package.
Thx

**Pull request closed without merging**
